module.exports = function loadCachedTemplates (we){
return {
  "layouts": {
    "we-theme-site-wejs/default": "<div class=\"container\"><div class=\"row\">\n  {{#region 'highlighted' class=\"col col-md-12\"}}{{/region}}\n\n  {{#region 'sidebar' class=\"col col-md-4\"}}{{/region}}\n  <div class=\"col col-md-8\">\n    <h1 class=\"page-header\">{{title}}</h1>\n\n    <div id=\"sysMessagesArea\">{{{we-messages}}}</div>\n\n    {{{body}}}\n  </div>\n</div></div>\n",
    "we-theme-site-wejs/wejsdoc": "<div class=\"container\"><div class=\"row\">\n  {{#region 'highlighted' class=\"col col-md-12\"}}{{/region}}\n\n  {{#region 'sidebar' class=\"col col-md-4\"}}{{/region}}\n  <div  id=\"content\" role=\"main\" class=\"col col-md-8\" style=\"min-height:450px\">\n    <div id=\"sysMessagesArea\">{{{we-messages}}}</div>\n\n    {{{body}}}\n\n    {{#region 'afterContent'}}{{/region}}\n  </div>\n  <div class=\"col col-md-8\">\n    <hr>\n    <p class=\"small\">Is something missing?<br>\n      If you notice something we've missed or could be improved on, please follow <a href=\"https://github.com/wejs/docs/tree/master/docs\">this link</a> and submit a pull request to the wejs/docs repo.</p>\n  </div>\n</div></div>\n",
    "we-theme-site-wejs/home": "<div id=\"page-wrapper\">\n  {{#region 'highlighted'}}{{/region}}\n  <div id=\"content\" role=\"main\">{{{body}}}</div>\n  {{#region 'afterContent'}}{{/region}}\n</div>\n",
    "we-theme-site-wejs/fullwidth": "<div id=\"page-wrapper\">\n  {{#region 'highlighted'}}{{/region}}\n  <div  id=\"content\" role=\"main\">{{{body}}}</div>\n  {{#region 'afterContent'}}{{/region}}\n</div>\n"
  },
  "templates": {
    "400": "<div class=\"container\">\n  <div class=\"jumbotron\">\n    <h1>{{t 'response.badRequest.title'}}</h1>\n    <p>{{t 'response.badRequest.description'}}</p>\n  </div>\n</div>",
    "403": "<div class=\"container\">\n  <div class=\"jumbotron\">\n    <h1>{{t 'response.forbidden.title'}}</h1>\n    <p>{{t 'response.forbidden.description'}}</p>\n  </div>\n</div>",
    "404": "<div class=\"container\">\n  <div class=\"jumbotron\">\n    <h1>{{t 'response.notFound.title'}}</h1>\n    <p>{{t 'response.notFound.description'}}</p>\n  </div>\n</div>",
    "500": "<div class=\"container\">\n  <div class=\"jumbotron\">\n    <h1>{{t 'response.serverError.title'}}</h1>\n    <p>{{t 'response.serverError.description'}}</p>\n  </div>\n</div>",
    "components-core": "{{#can permission='manage_widget' roleNames=req.userRoleNames}}\n{{!-- sort widget modal --}}\n<div aria-hidden=\"true\" class=\"modal\" id=\"sortWidgetFormModal\"><div class=\"modal-dialog modal-lg\"><div class=\"modal-content\"><div class=\"modal-header\"><button aria-hidden=\"true\" data-dismiss=\"modal\" class=\"close\" type=\"button\">×</button><h4 class=\"modal-title\">{{t 'widget.sort'}}</h4></div><div class=\"modal-body\"></div></div></div></div>\n{{!-- update widget modal --}}\n<div aria-hidden=\"true\" class=\"modal\" id=\"updateWidgetFormModal\"><div class=\"modal-dialog modal-lg\"><div class=\"modal-content\"><div class=\"modal-header\"><button aria-hidden=\"true\" data-dismiss=\"modal\" class=\"close\" type=\"button\">×</button><h4 class=\"modal-title\">{{t 'widget.update'}}</h4></div><div class=\"modal-body\"></div></div></div></div>\n{{!-- add widget form modal --}}\n<div aria-hidden=\"true\" class=\"modal\" id=\"AddWidgetFormModal\">\n<form>\n  <div class=\"modal-dialog modal-lg\">\n    <div class=\"modal-content\">\n      <div class=\"modal-header\">\n        <button aria-hidden=\"true\" data-dismiss=\"modal\" class=\"close\" type=\"button\">×</button><h4 class=\"modal-title\">{{t 'widget.add'}}</h4>\n      </div>\n      <div class=\"modal-body\">\n        <div class=\"steps-body\">\n          <div class=\"step1\">\n            <div class=\"form-group\">\n              <label>{{t 'layout.select.widget.type'}}</label>\n              <select id=\"AddWidgetFormModal-select-type\" name=\"type\" class=\"form-control\">\n                <option value=\"\"></option>\n              </select>\n            </div>\n            <div class=\"clearfix\"></div><hr>\n            <div class=\"form-group\">\n              <button type=\"button\" class=\"btn btn-primary\" onclick=\"we.structure.goToStep2();\"><i class=\"glyphicon glyphicon-step-forward\"></i> {{t 'Next'}}</button>\n            </div>\n          </div>\n          <div class=\"step2\"></div>\n        </div>\n      </div>\n    </div>\n  </div>\n</form>\n</div>\n{{/can}}\n<div class=\"system-actions\">\n  {{#can permission='manage_widget' roleNames=req.userRoleNames}}\n  <div class=\"we-layout-edit-btn\">\n    <button id=\"we-layout-start-edit-btn\" onclick=\"we.structure.showLayoutEditor();\" type=\"button\" class=\"btn btn-default btn-sm\"><i class=\"glyphicon glyphicon-edit text-info\"></i> {{t 'layout.edit.btn'}}</button>\n    <button id=\"we-layout-stop-edit-btn\" style=\"display:none;\" onclick=\"we.structure.hideLayoutEditor();\" type=\"button\" class=\"btn btn-default btn-sm\"><i class=\"glyphicon glyphicon-check text-success\"></i> {{t 'layout.edit.hide.btn'}}</button>\n  </div>\n  {{/can}}\n  {{#can permission='access_admin' roleNames=req.userRoleNames}}\n  <div class=\"we-admin-btn\">\n    <a href=\"/admin\" class=\"btn btn-default btn-sm\"><span class=\"glyphicon glyphicon-cog\"></span></a>\n  </div>\n  {{/can}}\n</div>",
    "default-layout": "{{#region 'highlighted' class=\"col col-md-12\"}}{{/region}}\n\n{{{body}}}",
    "messages": "{{#each messages}}\n  <div class=\"alert alert-{{status}} alert-dismissable\">\n    <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button>\n    {{{message}}}\n  </div>\n{{/each}}",
    "paginate": "<nav>\n  <ul class=\"pagination\">\n    {{#if previus}}\n      <li><a href=\"{{{previus.p}}}\" aria-label=\"Previous\">\n        <span aria-hidden=\"true\">&laquo;</span>\n      </a></li>\n    {{/if}}\n    {{#if haveMoreBefore}}\n      <li><a href=\"{{{first.p}}}\">\n        <span>{{{first.n}}}</span>\n      </a></li>\n      <li class=\"paginate-have-more-before disabled\">\n        <span>...</span>\n      </a></li>\n    {{/if}}\n    {{#each links}}\n      <li {{#if active}}class=\"active\"{{/if}}><a href=\"{{{p}}}\">{{{n}}}</a></li>\n    {{/each}}\n    {{#if haveMoreAfter}}\n      <li class=\"paginate-have-more-after disabled\"><a>\n        <span>...</span>\n      </a></li>\n      <li><a href=\"{{{last.p}}}\">\n        <span>{{{last.n}}}</span>\n      </a></li>\n    {{/if}}\n    {{#if next}}\n      <li><a href=\"{{{next.p}}}\" aria-label=\"Next\">\n        <span aria-hidden=\"true\">&raquo;</span>\n      </a></li>\n    {{/if}}\n  </ul>\n</nav>",
    "default/create": "{{{form-model model data validationError}}}",
    "default/delete": "<div class=\"text-center\">\n  <p>{{{t deleteMsg}}}</p>\n  <form method=\"post\">\n    <a class=\"btn btn-default\" href=\"{{redirectTo}}\">{{t 'Return'}}</a>\n    <button class=\"btn btn-danger\">{{t 'Delete'}}</button>\n    <input name=\"redirectTo\" type=\"hidden\" value=\"{{redirectTo}}\">\n  </form>\n</div>",
    "default/edit": "{{{form-model model data validationError}}}",
    "default/find": "<div class=\"actions\">\n{{we-action-create-btn resourceName req}}\n</div>\n<table class=\"table table-striped table-hover\">\n  <thead>\n    <tr>\n      <th>ID</th>\n      <th>{{t 'actions'}}</th>\n    </tr>\n  </thead>\n  <tbody>\n\n{{#each data}}\n  <tr>\n    <td>{{id}}</td>\n    <td>\n      {{we-action-view-btn ../resourceName this ../req id}}\n      {{we-action-edit-btn ../resourceName this ../req id}}\n      {{we-action-delete-btn ../resourceName this ../req id}}\n    </td>\n  </tr>\n{{/each}}\n\n  </tbody>\n  <tfoot>\n    <td colspan=\"2\">\n      {{paginate count=metadata.count limit=query.limit currentPage=query.page req=req}}\n    </td>\n  </tfoot>\n</table>",
    "default/findOne": "<table class=\"table table-striped table-hover\">\n  <tbody>\n    {{#each data.dataValues }}\n      <tr>\n        <th>{{@key}}</th>\n        <td>{{this}}</td>\n      </tr>\n    {{/each}}\n  </tbody>\n  <tfoot>\n    <td colspan=\"2\">\n      {{we-action-edit-btn resourceName data req data.id}}\n      {{we-action-delete-btn resourceName data req data.id}}\n    </td>\n  </tfoot>\n</table>",
    "admin/theme/index": "<table class=\"table\">\n  <thead>\n    <tr>\n      <th>{{t 'name'}}</th>\n      <th>Load as</th>\n      <th>{{t 'version'}}</th>\n      <th>{{t 'actions'}}</th>\n    </tr>\n  </thead>\n  <tbody>\n    {{#each themes}}\n      <tr>\n        <td>{{name}}</td>\n        <td>\n          {{#ifCond name ../themeConfigs.app}}\n            <span class=\"label label-success\">app</span>\n          {{/ifCond}}\n          {{#ifCond name ../themeConfigs.admin}}\n            <span class=\"label label-warning\">admin</span>\n          {{/ifCond}}\n        </td>\n        <td>{{version}}</td>\n        <td></td>\n      </tr>\n    {{/each}}\n  </tbody>\n</table>\n{{!--\n\n<form method=\"get\">\n  <h3>Search and install:</h3>\n  <div class=\"form-group\" >\n    <label for=\"findNewTheme\">Theme name:</label>\n    <input type=\"text\" class=\"form-control\" id=\"findNewTheme\" name=\"findNew\" value=\"{{req.query.findNew}}\">\n  </div>\n</form>\n\n{{#if searchedThemeInfo}}\n  <h4>{{req.query.findNew}} info:</h4>\n  <pre>{{searchedThemeInfo}}</pre>\n  <form method='post'>\n    <input type=\"hidden\" name=\"redirectTo\" value=\"{{req.url}}\">\n    <input type=\"hidden\" name=\"type\" value=\"theme\">\n    <input type=\"hidden\" name=\"name\" value=\"{{req.query.findNew}}\">\n    <div class=\"form-group\">\n      <button class=\"btn btn-primary\">Install</button>\n    </div>\n  </form>\n{{/if}}\n\n{{#if searchedThemeNotFound}}\n  <p>Not found</p>\n{{/if}} --}}",
    "we-theme-site-wejs/400": "bad request",
    "we-theme-site-wejs/403": "Forbidden page",
    "we-theme-site-wejs/404": "<br>\n<div class=\"jumbotron text-center\">\n  <h2>{{t 'not.found'}}</h2>\n  <p>404</p>\n  <p><a class=\"btn btn-primary btn-small\" href=\"/\" role=\"button\">{{t 'go.to'}} {{t 'home'}}</a></p>\n</div>",
    "we-theme-site-wejs/500": "Server Error",
    "we-theme-site-wejs/error": "error.hbs",
    "we-theme-site-wejs/html": "<!DOCTYPE html>\n<html lang=\"{{locale}}\">\n<head>\n  <title>{{title}} {{req.we.config.appName}}</title>\n\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\">\n\n  {{#unless metadata.image}}\n    <meta property=\"og:image\" content=\"{{req.we.config.hostname}}/public/plugin/we-core/files/images/logo.png\">\n  {{/unless}}\n  {{#unless metadata.description}}\n     <meta name=\"description\" content=\"Server side javascript framework for build real time applications, sites or blogs!\">\n     <meta property=\"og:description\" content=\"Server side javascript framework for build real time applications, sites or blogs!\">\n  {{/unless}}\n  {{#if _csrf}}<meta name=\"csrf-token\" content=\"{{_csrf}}\" />{{/if}}\n\n  {{{render-metadata-tags}}}\n  {{{render-stylesheet-tags}}}\n  {{{render-javascript-tags 'header'}}}\n</head>\n<body>\n  {{we-event event=\"we-html-body-start\"}}\n  {{{template 'partials/header'}}}\n  {{{layoutHtml}}}\n  {{{template 'partials/footer'}}}\n  {{we-event event=\"we-html-body-end\"}}\n</body>\n</html>",
    "we-theme-site-wejs/layout": "<div class=\"container\"><div class=\"row\">\n  {{#region 'highlighted' class=\"col col-md-12\"}}{{/region}}\n\n  {{#region 'sidebar' class=\"col col-md-4\"}}{{/region}}\n  <div class=\"col col-md-8\">\n    <h1 class=\"page-header\">{{title}}</h1>\n\n    <div id=\"sysMessagesArea\">{{{we-messages}}}</div>\n\n    {{{body}}}\n  </div>\n</div></div>\n",
    "we-theme-site-wejs/auth/login": "{{{form 'login' user}}}",
    "we-theme-site-wejs/auth/register": "{{#unless newUserCreated}}\n  {{{form 'register' data validationError}}}\n{{/unless}}",
    "we-theme-site-wejs/group/find": "",
    "we-theme-site-wejs/group/findOne": "",
    "we-theme-site-wejs/layouts/full-width-layout": "<div id=\"page-wrapper\">\n  {{#region 'highlighted'}}{{/region}}\n  <div  id=\"content\" role=\"main\">{{{body}}}</div>\n  {{#region 'afterContent'}}{{/region}}\n</div>\n",
    "we-theme-site-wejs/layouts/home": "<div id=\"page-wrapper\">\n  {{#region 'highlighted'}}{{/region}}\n  <div id=\"content\" role=\"main\">{{{body}}}</div>\n  {{#region 'afterContent'}}{{/region}}\n</div>\n",
    "we-theme-site-wejs/layouts/wejsdoc": "<div class=\"container\"><div class=\"row\">\n  {{#region 'highlighted' class=\"col col-md-12\"}}{{/region}}\n\n  {{#region 'sidebar' class=\"col col-md-4\"}}{{/region}}\n  <div  id=\"content\" role=\"main\" class=\"col col-md-8\" style=\"min-height:450px\">\n    <div id=\"sysMessagesArea\">{{{we-messages}}}</div>\n\n    {{{body}}}\n\n    {{#region 'afterContent'}}{{/region}}\n  </div>\n  <div class=\"col col-md-8\">\n    <hr>\n    <p class=\"small\">Is something missing?<br>\n      If you notice something we've missed or could be improved on, please follow <a href=\"https://github.com/wejs/docs/tree/master/docs\">this link</a> and submit a pull request to the wejs/docs repo.</p>\n  </div>\n</div></div>\n",
    "we-theme-site-wejs/partials/default-metadata": "<meta name=\"application-name\" content=\"{{sails.config.appName}}\">\n<meta name=\"application-url\" content=\"{{sails.config.hostname}}\">\n<meta name=\"description\" content=\"<%- sails.config.appDescription}}\">\n\n<meta property=\"og:site_name\" content=\"{{sails.config.appName}}\">\n<meta property=\"og:url\" content=\"{{sails.config.hostname}}\">\n<meta property=\"og:title\" content=\"{{sails.config.appName}}\">\n\n<meta property=\"og:description\" content=\"{{{sails.config.appDescription}}}\">\n\n<meta property=\"og:type\" content=\"application\">\n",
    "we-theme-site-wejs/partials/footer": "{{{render-bootstrap-config}}}\n{{{render-javascript-tags 'footer'}}}\n{{{render-client-component-templates}}}\n\n<script type=\"text/javascript\">\n  //Loads the correct sidebar on window load,\n  //collapses the sidebar on window resize.\n  // Sets the min-height of #page-wrapper to window size\n  $(function() {\n    $(window).bind(\"load resize\", function() {\n      topOffset = 50;\n      width = (this.window.innerWidth > 0) ? this.window.innerWidth : this.screen.width;\n      if (width < 768) {\n        $('div.navbar-collapse').addClass('collapse');\n        topOffset = 100; // 2-row-menu\n      } else {\n        $('div.navbar-collapse').removeClass('collapse');\n      }\n\n      height = ((this.window.innerHeight > 0) ? this.window.innerHeight : this.screen.height) - 1;\n      height = height - topOffset;\n      if (height < 1) height = 1;\n      if (height > topOffset) {\n        $(\"#page-wrapper\").css(\"min-height\", (height) + \"px\");\n      }\n    });\n  });\n</script>\n\n<hr>\n<div class=\"container\">\n<footer>\n  <div class=\"row\">\n    <div class=\"col-lg-12\">\n      <p>Code released under the <a href=\"#\">MIT License</a>.</p>\n    </div>\n  </div>\n</footer>\n</div>\n",
    "we-theme-site-wejs/partials/header": "<div class=\"navbar navbar-default\"><div class=\"container\">\n  <div class=\"navbar-header\">\n    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n      <span class=\"sr-only\">Toggle navigation</span>\n      <span class=\"icon-bar\"></span>\n      <span class=\"icon-bar\"></span>\n      <span class=\"icon-bar\"></span>\n    </button>\n    {{#link-to 'main.index' class=\"navbar-brand\"}}{{appName}}{{/link-to}}\n  </div>\n\n  {{we-menu req.we.menu.main}}\n\n  {{we-menu userMenu}}\n</div></div>",
    "we-theme-site-wejs/user/find": "static page for no javascript browsers",
    "we-theme-site-wejs/user/findOne": "<h1>{{data.displayName}}</h1> @{{data.username}}\n\n<p>{{data.biography}}</p>",
    "we-theme-site-wejs/user/usermenu": "<ul class=\"nav navbar-nav navbar-right\">\n  {{#if currentUser}}\n    <li class=\"dropdown\">\n      <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" id=\"download\" aria-expanded=\"true\">{{req.user.displayName}} <span class=\"caret\"></span></a>\n      <ul class=\"dropdown-menu\" aria-labelledby=\"download\">\n        <li>\n          {{#link-to 'user.findOne' req.user.id}}{{t 'Profile'}}{{/link-to}}\n        </li>\n        <li><a href=\"./bootstrap.css\">bootstrap.css</a></li>\n        <li class=\"divider\"></li>\n        <li><a href=\"./variables.less\">variables.less</a></li>\n        <li><a href=\"./bootswatch.less\">bootswatch.less</a></li>\n        <li class=\"divider\"></li>\n        <li><a href=\"./_variables.scss\">_variables.scss</a></li>\n        <li class=\"divider\"></li>\n        <li>{{#link-to 'auth.logout'}}\n          <i class=\"glyphicon glyphicon-log-out\"></i> {{t 'Logout'}}\n        {{/link-to}}</li>\n      </ul>\n    </li>\n\n  {{else}}\n    <li>{{#link-to 'auth.loginPage'}}{{t \"login.block.button.text\"}}{{/link-to}}</li>\n    <li>{{#link-to 'auth.signupPage'}}{{t \"login.block.form.new.account.link\"}}{{/link-to}}</li>\n  {{/if}}\n</ul>"
  }
}

};